### ISSUE TITLE
can't change project folder

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#1]
Currently my project folder is set to something like Drive/[big series of letters and numbers here]. This can be seen below:
![error](https://cloud.githubusercontent.com/assets/13293289/20782750/aa991528-b75c-11e6-8ee0-d8d1aebe0c89.PNG)

When I try updating it to the pertinent Drive folder, I receive the following error:
![error2](https://cloud.githubusercontent.com/assets/13293289/20782778/e9d0fa9e-b75c-11e6-87b3-ba9de45758c8.PNG)

I have tried clearing the cache and reinstalling the software.

**Comment by MrBlenny** [comment]
Hi Neil,
I have just released [v0.0.13](https://github.com/Stemn/Stemn-Desktop/releases/tag/v0.0.13) - with any luck that will fix this issue.

**Comment by neil1993** [comment]
This specific problem has been fixed. I've run into two other bugs but I'll open separate issues for those.
