### ISSUE TITLE
updating folder while commits are present breaks everything

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#10]
In a project where I already have 2 commits, I tried updating the folder. This resulted in the warning that doing so would erase the commit history. After confirming, I got an error message saying I was not the owner of the commit. 

After this I was no longer able to view the project files. Closing and reopening the program resulted in the error message that said the Cloud storage was not connected on the changes page. Only the changes page and the task page were available.

After re-selecting the appropriate folder in the project settings page, all the commits were still present.

**Comment by sabrehagen** [comment]
Thanks for finding this one Neil. We've fixed the bug and pushed to production.
