### ISSUE TITLE
owncloud / github

### ISSUE THREAD

**Issue by pciavald** [Stemn/Stemn-Desktop#12]
I see there's the possibility to host projects in Drive and Dropbox. Would it be possible to link : 
- an existing github repository
- an OwnCloud drive

**Comment by sabrehagen** [comment]
We are very much looking forward to integrating Stemn with more providers. Once we hear more from our community we'll know which cloud storage providers are most in demand. GitHub is likely the most popular in the foreseeable future.

**Comment by pciavald** [comment]
I understand. Even better than an OwnCloud connector, a webDAV one would cover almost any data storage, including OwnCloud.
