### ISSUE TITLE
Open Folder > Malformed URL

### ISSUE THREAD

**Issue by pciavald** [Stemn/Stemn-Desktop#13]
Distro : Manjaro / KDE

When I do Open Folder after clicking the project's name, there's a popup saying the file URL is malformed. This is the URL that is malformed : `\home/pciavald/Dropbox/STEMN`
As you can see, the first slash is a backwards one, which is not compatible with the Linux way of finding files.

**Comment by MrBlenny** [comment]
Thanks pciavald,
There are a few Linux related issues (including this) that I had been holding off doing. 
I'll have a look into this today.

**Comment by sabrehagen** [comment]
This will be fixed in the next release.
