### ISSUE TITLE
Error In Settings View

### ISSUE THREAD

**Issue by jmwright** [Stemn/Stemn-Desktop#15]
I'm running the latest AppImage on Ubuntu 16.04 64-bit. The app starts up fine, but I see the following error in the Settings view.

![screenshot_2017-07-18_09-22-55](https://user-images.githubusercontent.com/1015439/28319175-295fb28e-6b9b-11e7-9aa7-4b3eaa3bd83e.png)

**Comment by jmwright** [comment]
Just realized that there's an Application Info section of that settings screen.

![screenshot_2017-07-18_09-57-56](https://user-images.githubusercontent.com/1015439/28320881-bfd02862-6b9f-11e7-96f9-3920a10e7033.png)

**Comment by sabrehagen** [comment]
Thanks for reporting this. When running the application for the first time, did you get a prompt that [looked like this (except for Stemn)](https://camo.githubusercontent.com/40085a03302030b05a40027d79e4c0db42212102/68747470733a2f2f6e617468616e6a706c756d6d65722e6769746875622e696f2f427261636b6574732f696d616765732f617070696d6167652e6a7067)?

If you choose to integrate the app with your OS, our app will have the permissions to run at startup, and will be listed in Ubuntu's application launcher.

Alternatively, if you did see this dialog, clicked yes, and you're still seeing the red banner, then it is displaying in error and this is a bug.

**Comment by jmwright** [comment]
Yes, I saw that dialog and clicked the "Yes" button. There is an item in my system tray for your app, so I'm not sure why it thinks it's not integrated. I haven't tried creating a project yet, so maybe it's the Dropbox integration or something?

**Comment by sabrehagen** [comment]
We check for the existence of `${/home/you-user-name/.local/share/applications/appimagekit-STEMN.desktop` to know if the Yes button was clicked on the integration dialogue. I expect this file doesn't exist for you. Can you check if it exists on your system?

**Comment by jmwright** [comment]
The file that was created on my system has different capitalization `appimagekit-stemn.desktop`. With the Linux convention of case-sensitivity, it won't accept that as the same filename.

**Comment by sabrehagen** [comment]
Thanks, we will update the check to be case insensitive :) Fixed in the next release!

**Comment by jmwright** [comment]
Awesome, thanks.
