### ISSUE TITLE
Automatic Creation of Dropbox Project Folder Fails

### ISSUE THREAD

**Issue by jmwright** [Stemn/Stemn-Desktop#16]
When creating a project, I get to the "File Store" part of the dialog and it says "A new folder will be created in your dropbox". It creates a STEMN directory, but if I hit the Create button without selecting a directory manually, the app complains that "A project with that name already exists." Should it be creating a directory using the project's name, or do I need to create that manually?

**Comment by jmwright** [comment]
I guess I can't even create a directory manually and then select it. I get the same error.

**Comment by sabrehagen** [comment]
The "A project with that name already exists." was a limitation of our old site, but we can do away with it now. I've removed it and the code is on it's way to production.

In this instance, your project name "Test Project" was clashing with another existing project called "Test Project". This was a site wide restriction previously.
