### ISSUE TITLE
App Stops Responding After Creating a Project and Clicking on It

### ISSUE THREAD

**Issue by jmwright** [Stemn/Stemn-Desktop#17]
Not sure of the exact steps to reproduce yet, but after creating a project and seeing that the files sync'd in Dropbox, I clicked on the project in the left pane under "My Projects". Now I can't even close the app.

On Ubuntu 16.04 64-bit, version 0.0.24.

**Comment by jmwright** [comment]
I haven't actually experienced this problem again. I'll reopen this issue is it happens again and I can give the steps to reproduce it.

**Comment by sabrehagen** [comment]
Thanks Jeremy. There could have been some backend issues happening around the time you logged this that caused the app to hang. They've almost certainly been resolved. Please reopen if you encounter this again.
