### ISSUE TITLE
Logged out every time STEMN is shut down

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#2]
When I complete shut down STEMN on my computer and then restart it, I need to log in again instead of the program doing it automatically.

As well, the program forgets the folder for my cloud provider and that needs to be re-selected with every restart

**Comment by MrBlenny** [comment]
This should be fixed in [v0.0.14](https://github.com/Stemn/Stemn-Desktop/releases/tag/v0.0.14). 
If you are using the Windows or Linux version, Stemn Desktop should automatically begin updating to this version when the application starts.
