### ISSUE TITLE
Cloud storage folder selection for individual projects is generally messed up

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#3]
I can't really pin down a single bug here since it looks like there are a few on top of each other.

First, some folders cannot be selected. These are generally ones which have a lot of data in them or have not been created by me. It may be a privacy settings issue on the Drive side but I just can't figure it out.

Second, sometimes, once a folder has been selected, I can't switch to another folder. The selection window just has those 3 dots in the top left corner instead of displaying a folder path.

Third, when updating the folder (changing it from one to another) the folder will just not update. The update loading circle will not display and the previous file changes will remain in the changes tab.

**Comment by MrBlenny** [comment]
I've added a home button to the folder select modal in [v0.0.14](https://github.com/Stemn/Stemn-Desktop/releases/tag/v0.0.14). This will fix the 3 dots issue. I'm not quite what else is going wrong. 
@sabrehagen: will look into this.

**Comment by neil1993** [comment]
I'll spend some more time with the software and see if I can give you a better description of the problems I'm running into.

**Comment by neil1993** [comment]
I can confirm that the folder can now be switched.

First issue still remains

**Comment by neil1993** [comment]
First issue has been fixed. Closing the issue
