### ISSUE TITLE
Can't Find Dropbox on my machine

### ISSUE THREAD

**Issue by AlexRev** [Stemn/Stemn-Desktop#5]
Stemn can't find dropbox on my machine:
![image](https://cloud.githubusercontent.com/assets/8718134/21039541/cc3631de-be32-11e6-9525-d2d89bbe79d8.png)

**Comment by MrBlenny** [comment]
I've added something to debug this to `v0.0.15` - this should be out in the next day or so. Will look into it then.

**Comment by MrBlenny** [comment]
This is fixed in `v0.016`.
