### ISSUE TITLE
Render fails when loading assembly containing assemblies

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#7]
This may be a render error, or it may also be a file path error. I tried to load the main assembly of my project, which contains various smaller assemblies of sub-systems. The Sub-systems CAD is contained in sub-folders while the main assembly is kept in the parent folder. The error I got is as follows:
![capture](https://cloud.githubusercontent.com/assets/13293289/21248383/b1bdeef6-c304-11e6-96b7-9b09f28bb03e.PNG)

**Comment by sabrehagen** [comment]
Hi Neil, this has been fixed and will be part of the next release.
