### ISSUE TITLE
Folder structure not visible

### ISSUE THREAD

**Issue by neil1993** [Stemn/Stemn-Desktop#9]
Whenever I change the folder structure of my project, the change is not reflected in the changes page (especially if new parts have been placed in newly added folders).

To solve this, I need to update the project folder from the project settings page.

**Comment by sabrehagen** [comment]
Hi Neil, this seems to be an issue with old projects. We've recently changed the project data structure, and old projects didn't have the new data structure. Any new project you create will have changes propagated from your cloud provider to the app in real time. I'm going to close this as the next app release will have this fixed. We'll release a new version tomorrow.
